#!/bin/sh
# TODO: Replace with proper build system!

echo "Before continuing, make sure that you have the following programs installed:"
echo "+ ghc"
echo "+ cabal-install"
echo "+ clang"
echo "+ git"
echo "+ make"
echo "+ tar"
echo "+ wget"
read -p "Press any key to continue..."

SRC=$(pwd)
GC="8.0.4"
TMPDIR="/tmp/cognac-setup"

mkdir $TMPDIR

# Blocks Runtime
git clone https://github.com/mackyle/blocksruntime $TMPDIR/br
cd $TMPDIR/br
CC=clang ./buildlib
sudo ./installib
cd $TMPDIR
rm -rf $TMPDIR/br

# Boehm
cd $TMPDIR
wget https://www.hboehm.info/gc/gc_source/gc-$GC.tar.gz
tar xvfz gc-$GC.tar.gz
cd $TMPDIR/gc-$GC
./configure --prefix=/usr --disable-threads
make
make install
cd $TMPDIR
rm -rf $TMPDIR/gc-$GC
rm $TMPDIR/gc-$GC.tar.gz

# Install Split
cd $SRC
cabal update
cabal new-install split --lib # For new versions of cabal
cabal install split           # For old versions of cabal
