#!/usr/bin/env bash


# Clear log file
> tests/log.txt


# Iterate over files to test
for file in $(ls tests | grep .cog)
do
  echo "Testing $file..."
  # Compile
  ./cognac tests/$file > /dev/null
  # Check if file exists (successful compilation)
  if test -f "tests/$(echo $file | cut -f 1 -d '.')"; then
    # Run - outputting to logfile
    echo "PASS: $file compiles successfully" >> tests/log.txt
    ./tests/$(echo $file | cut -f 1 -d '.') 2>&1 >> tests/log.txt
  else
    # File not exists is error
    echo "FAIL: $file does not compile!" >> tests/log.txt
  fi
done

# Number of tests failed
while IFS= read -r line;
do
  if [[ ! $line == PASS:* ]]; then
    echo "Some tests failed! See log.txt."
    exit
  fi
done < ./tests/log.txt

echo "All tests passed!"
