#!/usr/bin/env bash

# Colour codes for printing
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Counter storing total tests failed
failed=0
# Counter storing total tests passed
passed=0

# Iterate over files to test
for file_name in $(ls tests | grep .cog | cut -f 1 -d '.')
do
  # file.cog
  source_file="tests/${file_name}.cog"
  # file.log
  log_file="tests/${file_name}.log"
  # $-12s pads with spaces
  printf 'Testing %-12s' $file_name'...'
  # Clear log file
  rm -f $log_file
  # Compile
  { cognac $source_file -run; } 2>>$log_file 1>&2
  # Check if any tests failed
  if [[ $(grep '^PASS:' $log_file) == $(<$log_file) ]]; then
    # If all tests passed
    ((passed++))
    echo -e "${GREEN} Pass ${NC}"
  else
    # If all tests failed
    ((failed++))
    echo -e "${RED} Fail ${NC}"
  fi
  # Delete binary
  rm -f $binary_file
done

if [[ $failed > 0 ]]; then
  echo -e "${RED}${failed} tests failed!${NC}"
  exit 1
else
  echo -e "${GREEN}All ${passed} tests passed!${NC}"
  exit 0
fi

