#!/usr/bin/env bash

# Colour codes for printing
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Iterate over files to test
for file_name in $(ls tests | grep .cog | cut -f 1 -d '.')
do
  source_file="tests/${file_name}.cog"
  binary_file="tests/${file_name}"
  log_file="tests/${file_name}.log"
  printf 'Testing %-12s' $file_name'...'
  # Clear log file
  > $log_file
  # Compile
  ./cognac $source_file -O0 "$@" > /tmp/cognac.log 2>&1
  # Check if file exists (successful compilation)
  if test -f $binary_file; then
    # Run - outputting to logfile
    { ./$binary_file; } 2>>$log_file 1>&2 # Segfaults will also be redirected to logfile
  else
    # File not exists is error
    echo "FAIL: '$file_name' does not compile!" >> $log_file
    # If it doesn't compile, put compiler errors in log.
    cat /tmp/cognac.log >> $log_file
  fi
  # Check if any tests failed
  if [[ $(grep '^PASS:' $log_file) == $(<$log_file) ]]; then
    echo -e "${GREEN} Pass ${NC}"
  else
    echo -e "${RED} Fail ${NC}"
  fi
done

rm /tmp/cognac.log
