{.name="ADD", .type=func, .argc=2, .args={number, number}, .rets=true, .ret=number},
{.name="SUB", .type=func, .argc=2, .args={number, number}, .rets=true, .ret=number},
{.name="MUL", .type=func, .argc=2, .args={number, number}, .rets=true, .ret=number},
{.name="DIV", .type=func, .argc=2, .args={number, number}, .rets=true, .ret=number},
{.name="GT",  .type=func, .argc=2, .args={number, number}, .rets=true, .ret=boolean},
{.name="GTE", .type=func, .argc=2, .args={number, number}, .rets=true, .ret=boolean},
{.name="LT",  .type=func, .argc=2, .args={number, number}, .rets=true, .ret=boolean},
{.name="LTE", .type=func, .argc=2, .args={number, number}, .rets=true, .ret=boolean},
{.name="EQ",  .type=func, .argc=2, .args={any, any},       .rets=true, .ret=boolean},
{.name="NEQ", .type=func, .argc=2, .args={any, any},       .rets=true, .ret=boolean},
{.name="if",    .type=func, .argc=3, .args={block, any, any},.rets=true, .ret=any, .needs_stack=true},
{.name="while", .type=func, .argc=2, .args={block, block}, .needs_stack=true},
{.name="print", .type=func, .argc=1, .args={any}},
{.name="put",   .type=func, .argc=1, .args={any}},
{.name="do", .type=func, .argc=1, .args={block}, .needs_stack=true},
{.name="random", .type=func, .argc=3, .args={number, number, number}, .rets=true, .ret=number},
{.name="modulo", .type=func, .argc=2, .args={number, number}, .rets=true, .ret=number},
{.name="drop", .type=stack_op, .stack_shuffle=&drop_register},
{.name="twin", .type=stack_op, .stack_shuffle=&twin_register},
{.name="triplet", .type=stack_op, .stack_shuffle=&triplet_register},
{.name="swap", .type=stack_op, .stack_shuffle=&swap_register},
{.name="clear", .type=func, .argc=0, .needs_stack=true},
{.name="true", .type=var, .rets=true, .ret=any},
{.name="false", .type=var, .rets=true, .ret=any},
{.name="either", .type=func, .argc=2, .args={boolean, boolean}, .rets=true, .ret=boolean},
{.name="both", .type=func, .argc=2, .args={boolean, boolean}, .rets=true, .ret=boolean},
{.name="one_of", .type=func, .argc=2, .args={boolean, boolean}, .rets=true, .ret=boolean},
{.name="not", .type=func, .argc=1, .args={boolean}, .rets=true, .ret=boolean},
{.name="number_", .type=func, .argc=1, .args={any}, .rets=true, .ret=boolean},
{.name="list_", .type=func, .argc=1, .args={any}, .rets=true, .ret=boolean},
{.name="string_", .type=func, .argc=1, .args={any}, .rets=true, .ret=boolean},
{.name="block_", .type=func, .argc=1, .args={any}, .rets=true, .ret=boolean},
{.name="boolean_", .type=func, .argc=1, .args={any}, .rets=true, .ret=boolean},
{.name="first", .type=func, .argc=1, .args={list}, .rets=true, .ret=any},
{.name="rest", .type=func, .argc=1, .args={list}, .rets=true, .ret=list},
{.name="head", .type=func, .argc=1, .args={string}, .rets=true, .ret=string},
{.name="tail", .type=func, .argc=1, .args={string}, .rets=true, .ret=string},
{.name="push", .type=func, .argc=2, .args={any, list}, .rets=true, .ret=list},
{.name="empty_", .type=func, .argc=1, .args={list}, .rets=true, .ret=boolean},
{.name="join", .type=func, .argc=1, .args={number}, .rets=true, .ret=string, .needs_stack=true},
{.name="string_length", .type=func, .argc=1, .args={string}, .rets=true, .ret=number},
{.name="substring", .type=func, .argc=3, .args={number, number, string}, .rets=true, .ret=string},
{.name="match", .type=func, .argc=2, .args={string, string}, .rets=true, .ret=boolean},
{.name="ordinal", .type=func, .argc=1, .args={string}, .rets=true, .ret=number},
{.name="character", .type=func, .argc=1, .args={number}, .rets=true, .ret=string},
{.name="floor", .type=func, .argc=1, .args={number}, .rets=true, .ret=number},
{.name="round", .type=func, .argc=1, .args={number}, .rets=true, .ret=number},
{.name="ceiling", .type=func, .argc=1, .args={number}, .rets=true, .ret=number},
{.name="assert", .type=func, .argc=1, .args={string,boolean}},
{.name="error", .type=func, .argc=1, .args={string}},
{.name="path", .type=func, .rets=true, .ret=string},
{.name="stack", .type=func, .rets=true, .ret=list, .needs_stack=true},
{.name="parameters", .type=func, .rets=true, .ret=list},
{.name="input", .type=func, .rets=true, .ret=string},
{.name="read", .type=func, .argc=1, .args={string}, .rets=true, .ret=string},
{.name="write", .type=func, .argc=1, .args={string,any}},
{.name="list", .type=func, .argc=1, .args={block}, .rets=true, .ret=list, .needs_stack=true},
{.name="number", .type=func, .argc=1, .args={string}, .rets=true, .ret=number},
{.name="map", .type=func, .argc=2, .args={block, list}, .rets=true, .ret=list, .needs_stack=true},
{.name="filter", .type=func, .argc=2, .args={block, list}, .rets=true, .ret=list, .needs_stack=true},
{.name="for", .type=func, .argc=2, .args={list, block}, .rets=false, .needs_stack=true},
{.name="range", .type=func, .argc=3, .args={number, number, number}, .rets=true, .ret=list},
{.name="table", .type=func, .argc=1, .args={block}, .rets=true, .ret=table, .needs_stack=true},
{.name="insert", .type=func, .argc=3, .args={symbol, any, table}, .rets=true, .ret=table},
{.name="get", .type=func, .argc=2, .args={symbol, table}, .rets=true, .ret=any},
{.name="stop"},
